config/routes.rb
Osra::Application.routes.draw do

  post '/partners/:partner_id/orphan_lists/:id/import' => 'orphan_lists#import', :as => :import_partner_orphan_list
  resources :partners, :except => [:destroy] do
    resources :orphan_lists
  end

  devise_for :users, :skip => [:registrations]

  resources :sponsors, :organizations

  resources :orphans , :except => [:new, :create, :destroy]

  root 'main#index'
  get '/locale/:id' => 'main#set_locale', :as => :set_locale

#
#
# get '/orphan_lists/validation' => 'orphan_lists#show_validation', :as => :show_validation#

# Example of regular route:
#   get 'products/:id' => 'catalog#view'

# Example of named route that can be invoked with purchase_url(id: product.id)
#   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

# Example resource route with concerns:
#   concern :toggleable do
#     post 'toggle'
#   end
#   resources :posts, concerns: :toggleable
#   resources :photos, concerns: :toggleable

# Example resource route within a namespace:
#   namespace :admin do
#     # Directs /admin/products/* to Admin::ProductsController
#     # (app/controllers/admin/products_controller.rb)
#     resources :products
#   end
end

app/models/sponsor.rb
class Sponsor
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::MultiParameterAttributes

  belongs_to :organization

  field :name
  field :status
  field :type
  field :branch
  field :gender
  field :address
  field :country
  field :partnership_start_date, type: Date
  field :email
  field :contact_1
  field :contact_2
  field :additional_info
  field :osra_id, type: Integer

  validates_presence_of :branch

end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_action :set_sponsor, only: [:show, :edit, :update, :destroy]

  # GET /sponsors
  # GET /sponsors.json
  def index
    @sponsors = Sponsor.all
  end

  # GET /sponsors/1
  # GET /sponsors/1.json
  def show
  end

  # GET /sponsors/new
  def new
    @sponsor = Sponsor.new
  end

  # GET /sponsors/1/edit
  def edit
  end

  # POST /sponsors
  # POST /sponsors.json
  def create
    @sponsor = Sponsor.new(sponsor_params)

    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sponsor }
      else
        format.html { render action: 'new' }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sponsors/1
  # PATCH/PUT /sponsors/1.json
  def update
    respond_to do |format|
      if @sponsor.update(sponsor_params)
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1
  # DELETE /sponsors/1.json
  def destroy
    @sponsor.destroy
    respond_to do |format|
      format.html { redirect_to sponsors_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_sponsor
    @sponsor = Sponsor.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sponsor_params
    params.require(:sponsor).permit(:name, :branch, :status, :type, :organization_id, :gender, :address, :country, :partnership_start_date, :email, :contact_1, :contact_2, :additional_info, :osra_id)
  end
end

app/views/sponsors/_form.html.erb
<%= form_for @sponsor, :html => {:class => 'form-horizontal'} do |f| %>
    <% if @sponsor.errors.any? %>
        <div class="alert alert-danger" id="error_explanation">
          <h4><%= t 'messages.error.validation', :default => "Validation errors:" %></h4>
          <ul>
            <% @sponsor.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :branch, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :branch, (option_values 'branches') %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :status, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :status, (option_values 'statuses') %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :type, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :type, (option_values 'sponsor_types') %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :organization_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :organization_id, Organization.all.map { |o| [o.name, o.id] }, :include_blank => true %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :gender, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :gender, (option_values 'genders') %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :address, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :address, :class => 'text_area' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :country, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :country, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :partnership_start_date, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :partnership_start_date, "data-behaviour" => 'datepicker' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.email_field :email, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :contact_1, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :contact_1, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :contact_2, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :contact_2, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :additional_info, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :additional_info, :class => 'text_field' %>
      </div>
    </div>


    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  sponsors_path, :class => 'btn' %>
    </div>
<% end %>

app/views/sponsors/edit.html.erb
<%- model_class = Sponsor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sponsors/index.html.erb
<%- model_class = Sponsor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:organization_id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:branch) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:type) %></th>
      <th><%= model_class.human_attribute_name(:gender) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%= model_class.human_attribute_name(:country) %></th>
      <th><%= model_class.human_attribute_name(:partnership_start_date) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:contact_1) %></th>
      <th><%= model_class.human_attribute_name(:contact_2) %></th>
      <th><%= model_class.human_attribute_name(:additional_info) %></th>
      <th><%= model_class.human_attribute_name(:osra_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sponsors.each do |sponsor| %>
      <tr>
        <td><%= link_to sponsor.id, sponsor_path(sponsor) %></td>
        <td><%= sponsor.organization.name rescue '' %></td>
        <td><%= sponsor.name %></td>
        <td><%= t_option 'branches', sponsor.branch %></td>
        <td><%= sponsor.status %></td>
        <td><%= sponsor.type %></td>
        <td><%= sponsor.gender %></td>
        <td><%= sponsor.address %></td>
        <td><%= sponsor.country %></td>
        <td><%= sponsor.partnership_start_date %></td>
        <td><%= sponsor.email %></td>
        <td><%= sponsor.contact_1 %></td>
        <td><%= sponsor.contact_2 %></td>
        <td><%= sponsor.additional_info %></td>
        <td><%= sponsor.osra_id %></td>
        <td><%=l sponsor.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sponsor_path(sponsor), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      sponsor_path(sponsor),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sponsor_path,
            :class => 'btn btn-primary' %>

app/views/sponsors/new.html.erb
<%- model_class = Sponsor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sponsors/show.html.erb
<%- model_class = Sponsor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:organization_id) %>:</strong></dt>
  <dd><%= @sponsor.organization.name rescue '' %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @sponsor.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @sponsor.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:branch) %>:</strong></dt>
  <dd><%= t_option 'branches', @sponsor.branch %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type) %>:</strong></dt>
  <dd><%= @sponsor.type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gender) %>:</strong></dt>
  <dd><%= @sponsor.gender %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @sponsor.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country) %>:</strong></dt>
  <dd><%= @sponsor.country %></dd>
  <dt><strong><%= model_class.human_attribute_name(:partnership_start_date) %>:</strong></dt>
  <dd><%= @sponsor.partnership_start_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @sponsor.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact_1) %>:</strong></dt>
  <dd><%= @sponsor.contact_1 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact_2) %>:</strong></dt>
  <dd><%= @sponsor.contact_2 %></dd>
  <dt><strong><%= model_class.human_attribute_name(:additional_info) %>:</strong></dt>
  <dd><%= @sponsor.additional_info %></dd>
  <dt><strong><%= model_class.human_attribute_name(:osra_id) %>:</strong></dt>
  <dd><%= @sponsor.osra_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              sponsors_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sponsor_path(@sponsor), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sponsor_path(@sponsor),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>