config/routes.rb
Osra::Application.routes.draw do

  post '/partners/:partner_id/orphan_lists/:id/import' => 'orphan_lists#import', :as => :import_partner_orphan_list
  resources :partners, :except => [:destroy] do
    resources :orphan_lists
  end

  devise_for :users, :skip => [:registrations]

  resources :sponsors, :organizations

  resources :orphans , :except => [:new, :create, :destroy]

  root 'main#index'
  get '/locale/:id' => 'main#set_locale', :as => :set_locale

#
#
# get '/orphan_lists/validation' => 'orphan_lists#show_validation', :as => :show_validation#

# Example of regular route:
#   get 'products/:id' => 'catalog#view'

# Example of named route that can be invoked with purchase_url(id: product.id)
#   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

# Example resource route with concerns:
#   concern :toggleable do
#     post 'toggle'
#   end
#   resources :posts, concerns: :toggleable
#   resources :photos, concerns: :toggleable

# Example resource route within a namespace:
#   namespace :admin do
#     # Directs /admin/products/* to Admin::ProductsController
#     # (app/controllers/admin/products_controller.rb)
#     resources :products
#   end
end

app/models/orphan.rb
class Orphan
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::AutoInc

  after_create :set_osra_id

  field :name
  field :father_name
  field :father_is_martyr, type: Boolean
  field :father_occupation
  field :father_place_of_death
  field :father_cause_of_death
  field :father_date_of_death, type: Date
  field :mother_name
  field :mother_alive, type: Boolean
  field :date_of_birth, type: Date
  field :gender
  field :health_status
  field :schooling_status
  field :goes_to_school, type: Boolean
  field :guardian_name
  field :guardian_relationship
  field :guardian_id
  field :original_address_gov, type: Integer
  field :original_address_city
  field :original_address_neighborhood
  field :original_address_street
  field :original_address_details
  field :current_address_gov, type: Integer
  field :current_address_city
  field :current_address_neighborhood
  field :current_address_street
  field :current_address_details
  field :contact_number
  field :alt_contact_number
  field :sponsored_by_another_org, type: Boolean
  field :another_org_sponsorship_details
  field :minor_siblings_count, type: Integer
  field :sponsored_minor_siblings_count, type: Integer
  field :comments

  field :partner_gov, type: Integer

  field :status, default: Settings.statuses[1]

  field :osra_id

  belongs_to :orphan_list

  auto_increment :seq, :scope => :partner_gov

  validates_presence_of :name, :father_name, :father_is_martyr, :father_date_of_death,
                        :mother_name, :mother_alive, :date_of_birth, :gender, :original_address_gov,
                        :original_address_city, :original_address_neighborhood, :current_address_gov,
                        :current_address_city, :current_address_neighborhood, :contact_number,
                        :sponsored_by_another_org, :minor_siblings_count

  def set_osra_id
    update!(:osra_id => '%d%05d' % [partner_gov, seq])
  end

  def to_param
    osra_id.to_s
  end

end

app/controllers/orphans_controller.rb
class OrphansController < ApplicationController
  before_action :set_orphan, only: [:show, :edit, :update, :destroy]

  # GET /orphans
  # GET /orphans.json
  def index
    @orphans = Orphan.all
  end

  # GET /orphans/1
  # GET /orphans/1.json
  def show
  end

  # GET /orphans/new
  def new
    @orphan = Orphan.new
  end

  # GET /orphans/1/edit
  def edit
  end

  # POST /orphans
  # POST /orphans.json
  def create
    @orphan = Orphan.new(orphan_params)

    respond_to do |format|
      if @orphan.save
        format.html { redirect_to @orphan, notice: 'Orphan was successfully created.' }
        format.json { render action: 'show', status: :created, location: @orphan }
      else
        format.html { render action: 'new' }
        format.json { render json: @orphan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orphans/1
  # PATCH/PUT /orphans/1.json
  def update
    respond_to do |format|
      if @orphan.update(orphan_params)
        format.html { redirect_to @orphan, notice: 'Orphan was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @orphan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orphans/1
  # DELETE /orphans/1.json
  def destroy
    @orphan.destroy
    respond_to do |format|
      format.html { redirect_to orphans_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_orphan
    @orphan = Orphan.find_by(osra_id: params[:id])
  end


  # Never trust parameters from the scary internet, only allow the white list through.
  def orphan_params
    params.require(:orphan).permit(:orphan_list, :name, :father_name, :father_is_martyr, :father_occupation, :father_place_of_death, :father_cause_of_death, :father_date_of_death, :mother_name, :mother_alive, :gender, :health_status, :schooling_status, :goes_to_school, :guardian_name, :guardian_relationship, :guardian_id, :original_address_gov, :original_address_city, :original_address_neighborhood, :original_address_street, :original_address_details, :current_address_gov, :current_address_city, :current_address_neighborhood, :current_address_street, :current_address_details, :contact_number, :alt_contact_number, :sponsored_by_another_org, :another_org_sponsorship_details, :minor_siblings_count, :sponsored_minor_siblings_count, :comments)
  end
end

app/views/orphans/_form.html.erb
<%= form_for @orphan, :html => {:class => 'form-horizontal'} do |f| %>
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :health_status, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :health_status, :class => 'text_field' %>
      </div>
    </div>

    <hr>
    <h4>Parents' Information:</h4>

    <div class="control-group">
      <%= f.label :father_name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :father_name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :father_is_martyr, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :father_is_martyr, (option_values 'father_is_martyr') %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :father_occupation, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :father_occupation, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :father_place_of_death, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :father_place_of_death, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :father_cause_of_death, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :father_cause_of_death, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :father_date_of_death, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :father_date_of_death, "data-behaviour" => 'datepicker' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :mother_name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :mother_name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :mother_alive, :class => 'control-label' %>
      <div class="controls">
        <%= f.check_box :mother_alive %>
      </div>
    </div>

    <hr>
    <h4>Orphan Information:</h4>

    <div class="control-group">
      <%= f.label :date_of_birth, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :date_of_birth, "data-behaviour" => 'datepicker' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :gender, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :gender, (option_values 'genders') %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :schooling_status, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :schooling_status, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :goes_to_school, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :goes_to_school, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :guardian_name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :guardian_name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :guardian_relationship, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :guardian_relationship, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :guardian_id, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :guardian_id, :class => 'text_field' %>
      </div>
    </div>

    <hr>
    <h4>Original Address:</h4>


    <div class="control-group">
      <%= f.label :original_address_gov, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :original_address_gov, (option_values 'governorates') %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :original_address_city, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :original_address_city, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :original_address_neighborhood, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :original_address_neighborhood, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :original_address_street, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :original_address_street, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :original_address_details, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :original_address_details, :class => 'text_field' %>
      </div>
    </div>
    <hr>
    <h4>Current Address:</h4>

    <div class="control-group">
      <%= f.label :current_address_gov, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :current_address_gov, (option_values 'governorates') %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :current_address_city, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :current_address_city, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :current_address_neighborhood, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :current_address_neighborhood, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :current_address_street, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :current_address_street, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :current_address_details, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :current_address_details, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :contact_number, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :contact_number, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :alt_contact_number, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :alt_contact_number, :class => 'text_field' %>
      </div>
    </div>

    <hr>
    <h4>Additional Information:</h4>


    <div class="control-group">
      <%= f.label :sponsored_by_another_org, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :sponsored_by_another_org, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :another_org_sponsorship_details, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :another_org_sponsorship_details, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :minor_siblings_count, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :minor_siblings_count, :type => 'number', :min => 0 %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :sponsored_minor_siblings_count, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :sponsored_minor_siblings_count, :type => 'number', :min => 0 %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :comments, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :comments, :class => 'text_field' %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  orphans_path, :class => 'btn' %>
    </div>
<% end %>

app/views/orphans/edit.html.erb
<% model_class = Orphan %>
<div class="page-header">
  <h1><%= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/orphans/index.html.erb
<% model_class = Orphan %>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:father_name) %></th>
    <th><%= model_class.human_attribute_name(:father_is_martyr) %></th>
    <th><%= model_class.human_attribute_name(:status) %></th>

    <th><%= model_class.human_attribute_name(:mother_name) %></th>
    <th><%= model_class.human_attribute_name(:mother_alive) %></th>
    <th><%= model_class.human_attribute_name(:gender) %></th>
    <th><%= model_class.human_attribute_name(:date_of_birth) %></th>

    <th><%= model_class.human_attribute_name(:original_address_gov) %></th>
    <th><%= model_class.human_attribute_name(:original_address_city) %></th>

    <th><%= model_class.human_attribute_name(:current_address_gov) %></th>
    <th><%= model_class.human_attribute_name(:current_address_city) %></th>

    <th><%= model_class.human_attribute_name(:contact_number) %></th>

    <th><%= model_class.human_attribute_name(:sponsored_by_another_org) %></th>

  </tr>
  </thead>
  <tbody>
  <% @orphans.each do |orphan| %>
      <tr>
        <td><%= link_to orphan.osra_id, orphan_path(orphan) %></td>
        <td><%= orphan.name %></td>
        <td><%= orphan.father_name %></td>
        <td><%= t_option 'father_is_martyr', orphan.father_is_martyr %></td>
        <td><%= t_option 'statuses', orphan.status %></td>

        <td><%= orphan.mother_name %></td>
        <td><%= t_option 'mother_alive', orphan.mother_alive %></td>
        <td><%= t_option 'genders', orphan.gender %></td>
        <td><%= orphan.date_of_birth %></td>

        <td><%= t_option 'governorates', orphan.original_address_gov %></td>
        <td><%= orphan.original_address_city %></td>

        <td><%= t_option 'governorates', orphan.current_address_gov %></td>
        <td><%= orphan.current_address_city %></td>

        <td><%= orphan.contact_number %></td>

        <td><%= orphan.sponsored_by_another_org %></td>

      </tr>
  <% end %>
  </tbody>
</table>

app/views/orphans/show.html.erb
<% model_class = Orphan %>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:osra_id) %>:</strong></dt>
  <dd><%= @orphan.osra_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @orphan.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= t_option 'statuses', @orphan.status %></dd>

  <hr>
  <h4>Parents' Information:</h4>

  <dt><strong><%= model_class.human_attribute_name(:father_name) %>:</strong></dt>
  <dd><%= @orphan.father_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:father_is_martyr) %>:</strong></dt>
  <dd><%= t_option 'father_is_martyr', @orphan.father_is_martyr %></dd>
  <dt><strong><%= model_class.human_attribute_name(:father_occupation) %>:</strong></dt>
  <dd><%= @orphan.father_occupation %></dd>
  <dt><strong><%= model_class.human_attribute_name(:father_place_of_death) %>:</strong></dt>
  <dd><%= @orphan.father_place_of_death %></dd>
  <dt><strong><%= model_class.human_attribute_name(:father_cause_of_death) %>:</strong></dt>
  <dd><%= @orphan.father_cause_of_death %></dd>
  <dt><strong><%= model_class.human_attribute_name(:father_date_of_death) %>:</strong></dt>
  <dd><%= @orphan.father_date_of_death %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mother_name) %>:</strong></dt>
  <dd><%= @orphan.mother_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mother_alive) %>:</strong></dt>
  <dd><%= t_option 'mother_alive', @orphan.mother_alive %></dd>

  <hr>
  <h4>Orphan Information:</h4>

  <dt><strong><%= model_class.human_attribute_name(:date_of_birth) %>:</strong></dt>
  <dd><%= @orphan.date_of_birth %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gender) %>:</strong></dt>
  <dd><%= @orphan.gender %></dd>
  <dt><strong><%= model_class.human_attribute_name(:health_status) %>:</strong></dt>
  <dd><%= @orphan.health_status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:schooling_status) %>:</strong></dt>
  <dd><%= @orphan.schooling_status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:goes_to_school) %>:</strong></dt>
  <dd><%= @orphan.goes_to_school %></dd>
  <dt><strong><%= model_class.human_attribute_name(:guardian_name) %>:</strong></dt>
  <dd><%= @orphan.guardian_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:guardian_relationship) %>:</strong></dt>
  <dd><%= @orphan.guardian_relationship %></dd>
  <dt><strong><%= model_class.human_attribute_name(:guardian_id) %>:</strong></dt>
  <dd><%= @orphan.guardian_id %></dd>

  <hr>
  <h4>Original Address:</h4>

  <dt><strong><%= model_class.human_attribute_name(:original_address_gov) %>:</strong></dt>
  <dd><%= t_option 'governorates', @orphan.original_address_gov %></dd>
  <dt><strong><%= model_class.human_attribute_name(:original_address_city) %>:</strong></dt>
  <dd><%= @orphan.original_address_city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:original_address_neighborhood) %>:</strong></dt>
  <dd><%= @orphan.original_address_neighborhood %></dd>
  <dt><strong><%= model_class.human_attribute_name(:original_address_street) %>:</strong></dt>
  <dd><%= @orphan.original_address_street %></dd>
  <dt><strong><%= model_class.human_attribute_name(:original_address_details) %>:</strong></dt>
  <dd><%= @orphan.original_address_details %></dd>

  <hr>
  <h4>Current Address:</h4>

  <dt><strong><%= model_class.human_attribute_name(:current_address_gov) %>:</strong></dt>
  <dd><%= t_option 'governorates', @orphan.current_address_gov %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_address_city) %>:</strong></dt>
  <dd><%= @orphan.current_address_city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_address_neighborhood) %>:</strong></dt>
  <dd><%= @orphan.current_address_neighborhood %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_address_street) %>:</strong></dt>
  <dd><%= @orphan.current_address_street %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_address_details) %>:</strong></dt>
  <dd><%= @orphan.current_address_details %></dd>
  <dt><strong><%= model_class.human_attribute_name(:contact_number) %>:</strong></dt>
  <dd><%= @orphan.contact_number %></dd>
  <dt><strong><%= model_class.human_attribute_name(:alt_contact_number) %>:</strong></dt>
  <dd><%= @orphan.alt_contact_number %></dd>

  <hr>
  <h4>Additional Information:</h4>

  <dt><strong><%= model_class.human_attribute_name(:sponsored_by_another_org) %>:</strong></dt>
  <dd><%= @orphan.sponsored_by_another_org %></dd>
  <dt><strong><%= model_class.human_attribute_name(:another_org_sponsorship_details) %>:</strong></dt>
  <dd><%= @orphan.another_org_sponsorship_details %></dd>
  <dt><strong><%= model_class.human_attribute_name(:minor_siblings_count) %>:</strong></dt>
  <dd><%= @orphan.minor_siblings_count %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sponsored_minor_siblings_count) %>:</strong></dt>
  <dd><%= @orphan.sponsored_minor_siblings_count %></dd>
  <dt><strong><%= model_class.human_attribute_name(:comments) %>:</strong></dt>
  <dd><%= @orphan.comments %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              orphans_path, :class => 'btn' %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_orphan_path(@orphan), :class => 'btn' %>
</div>