config/routes.rb
Osra::Application.routes.draw do

  post '/partners/:partner_id/orphan_lists/:id/import' => 'orphan_lists#import', :as => :import_partner_orphan_list
  resources :partners, :except => [:destroy] do
    resources :orphan_lists
  end

  devise_for :users, :skip => [:registrations]

  resources :sponsors, :organizations

  resources :orphans , :except => [:new, :create, :destroy]

  root 'main#index'
  get '/locale/:id' => 'main#set_locale', :as => :set_locale

#
#
# get '/orphan_lists/validation' => 'orphan_lists#show_validation', :as => :show_validation#

# Example of regular route:
#   get 'products/:id' => 'catalog#view'

# Example of named route that can be invoked with purchase_url(id: product.id)
#   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

# Example resource route with concerns:
#   concern :toggleable do
#     post 'toggle'
#   end
#   resources :posts, concerns: :toggleable
#   resources :photos, concerns: :toggleable

# Example resource route within a namespace:
#   namespace :admin do
#     # Directs /admin/products/* to Admin::ProductsController
#     # (app/controllers/admin/products_controller.rb)
#     resources :products
#   end
end

app/models/organization.rb
class Organization
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::MultiParameterAttributes
  include Mongoid::AutoInc

  after_create :set_osra_id

  field :name
  field :country
  field :region
  field :partnership_start_date, type: Date
  field :status
  field :osra_id

  auto_increment :seq

  def set_osra_id
    update!(:osra_id => '%03d' % seq)
  end

  has_many :sponsors

  validates_presence_of :name, :country, :status

  def to_param
    osra_id.to_s
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render action: 'show', status: :created, location: @organization }
      else
        format.html { render action: 'new' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_organization
    @organization = Organization.find_by(osra_id: params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def organization_params
    params.require(:organization).permit(:name, :country, :region, :partnership_start_date, :status, :osra_id)
  end
end

app/views/organizations/_form.html.erb
<%= form_for @organization, :html => {:class => 'form-horizontal'} do |f| %>

    <% if @organization.errors.any? %>
        <div class="alert alert-danger" id="error_explanation">
          <h4><%= t 'messages.error.validation', :default => "Validation errors:" %></h4>
          <ul>
            <% @organization.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :country, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :country, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :region, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :region, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :partnership_start_date, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :partnership_start_date, "data-behaviour" => 'datepicker' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :status, :class => 'control-label' %>
      <div class="controls">
        <%= f.select :status, (option_values 'statuses') %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  organizations_path, :class => 'btn' %>
    </div>
<% end %>

app/views/organizations/edit.html.erb
<%- model_class = Organization -%>
<div class="page-header">
  <h1><%= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/organizations/index.html.erb
<% model_class = Organization %>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:osra_id) %></th>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:country) %></th>
    <th><%= model_class.human_attribute_name(:region) %></th>
    <th><%= model_class.human_attribute_name(:partnership_start_date) %></th>
    <th><%= model_class.human_attribute_name(:status) %></th>
    <th><%= t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @organizations.each do |organization| %>
      <tr>
        <td><%= link_to organization.osra_id, organization_path(organization) %></td>
        <td><%= organization.name %></td>
        <td><%= organization.country %></td>
        <td><%= organization.region %></td>
        <td><%= organization.partnership_start_date %></td>
        <td><%= t_option 'statuses', organization.status %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_organization_path(organization), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      organization_path(organization),
                      :method => :delete,
                      :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_organization_path,
            :class => 'btn btn-primary' %>

app/views/organizations/new.html.erb
<%- model_class = Organization -%>
<div class="page-header">
  <h1><%= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/organizations/show.html.erb
<%- model_class = Organization -%>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:osra_id) %>:</strong></dt>
  <dd><%= @organization.osra_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @organization.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country) %>:</strong></dt>
  <dd><%= @organization.country %></dd>
  <dt><strong><%= model_class.human_attribute_name(:region) %>:</strong></dt>
  <dd><%= @organization.region %></dd>
  <dt><strong><%= model_class.human_attribute_name(:partnership_start_date) %>:</strong></dt>
  <dd><%= @organization.partnership_start_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= t_option 'statuses', @organization.status %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              organizations_path, :class => 'btn' %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_organization_path(@organization), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              organization_path(@organization),
              :method => 'delete',
              :data => {:confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?'))},
              :class => 'btn btn-danger' %>
</div>