config/routes.rb
Osra::Application.routes.draw do

  post '/partners/:partner_id/orphan_lists/:id/import' => 'orphan_lists#import', :as => :import_partner_orphan_list
  resources :partners, :except => [:destroy] do
    resources :orphan_lists
  end

  devise_for :users, :skip => [:registrations]

  resources :sponsors, :organizations

  resources :orphans , :except => [:new, :create, :destroy]

  root 'main#index'
  get '/locale/:id' => 'main#set_locale', :as => :set_locale

#
#
# get '/orphan_lists/validation' => 'orphan_lists#show_validation', :as => :show_validation#

# Example of regular route:
#   get 'products/:id' => 'catalog#view'

# Example of named route that can be invoked with purchase_url(id: product.id)
#   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

# Example resource route with concerns:
#   concern :toggleable do
#     post 'toggle'
#   end
#   resources :posts, concerns: :toggleable
#   resources :photos, concerns: :toggleable

# Example resource route within a namespace:
#   namespace :admin do
#     # Directs /admin/products/* to Admin::ProductsController
#     # (app/controllers/admin/products_controller.rb)
#     resources :products
#   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : 'OSRA' %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body class="<%= I18n.locale == :ar ? "rtl" : "ltr" %>">

<div class="navbar navbar-fluid-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">OSRA</a>

      <div class="container-fluid nav-collapse">
        <ul class="nav">
          <% if user_signed_in? %>
              <li><%= link_to "Orphans", orphans_path %></li>
              <li><%= link_to "Partners", partners_path %></li>
              <li><%= link_to "Organizations", organizations_path %></li>
              <li><%= link_to "Sponsors", sponsors_path %></li>
              <li style="padding: 10px 15px 10px;"><%= "Welcome #{current_user.name}"%></li>
              <li>
                <% if I18n.locale == :ar %>
                    <%= link_to "EN", set_locale_path('en') %>
                <% else %>
                    <%= link_to "AR", set_locale_path('ar') %>
                <% end %>
              </li>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></div></li>
          <% end %>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span12">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div>
  <!--/row-->

  <footer>
    <p>&copy; OSRA 2014</p>
  </footer>

</div>
<!-- /container -->

</body>
</html>